version: "3"

services:
  database-test:
    image: library/postgres:14
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'postgres'
    ports:
      - "5433:5432"
